[[dependencies]]
repo = "https://github.com/hyperium/tonic"
branch = "v0.7.2"
src = "examples/proto/echo/echo.proto"
dst = "proto-ext/echo.proto"

[[dependencies]]
repo = "https://github.com/hyperium/tonic"
branch = "v0.6.0"
src = "examples/proto/helloworld/helloworld.proto"
dst = "proto-ext/helloworld_v0_6_0.proto"

[[dependencies]]
repo = "https://github.com/hyperium/tonic"
branch = "v0.7.2"
src = "examples/proto/helloworld/helloworld.proto"
dst = "proto-ext/helloworld_v0_7_2.proto"
